apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-demo-deployment
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-demo
  template:
    metadata:
      labels:
        app: wordpress-demo
    spec:
      # initContainers:
      # - name: init-permissions
      #   image: busybox
      #   command: ["sh", "-c", "chown -R 33:33 /var/www/html/wp-content/uploads"]
        # volumeMounts:
        # - name: wordpress-demo-pvc
        #   mountPath: /var/www/html/wp-content/uploads

      containers:
      - name: wordpress-demo
        image: devidevops447/wordpress-demo-beta:v22
        ports:
        - containerPort: 80
        # volumeMounts:
        # - name: wordpress-demo-pvc
        #   mountPath: /var/www/html/wp-content/uploads
        # - name: wp-config-volume
        #   mountPath: /var/www/html/wp-config.php
        #   subPath: wp-config.php
        # env:
        # - name: wordpress-demo_DB_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: wordpress-demo-secret
        #       key: wordpress-demo_DB_HOST
        # - name: wordpress-demo_DB_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: wordpress-demo-secret
        #       key: wordpress-demo_DB_NAME
        # - name: wordpress-demo_DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: wordpress-demo-secret
        #       key: wordpress-demo_DB_USER
        # - name: wordpress-demo_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: wordpress-demo-secret
        #       key: wordpress-demo_DB_PASSWORD

      # volumes:
      # - name: wp-config-volume
      #   configMap:
      #     name: wp-config
      # - name: wordpress-demo-pvc
      #   persistentVolumeClaim:
      #     claimName: wordpress-demo-pvc
