apiVersion: v1
kind: Service
metadata:
  name: wordpress-demo-service
  namespace: workshop
spec:
  type: NodePort
  selector:
    app: wordpress-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30012
