apiVersion: v1
kind: Service
metadata:
  name: reactjs-frontend-service
  labels:
    app: reactjs-frontend
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: reactjs-frontend