apiVersion: v1
kind: Service
metadata:
  name: wreactjs-frontend-service
  namespace: workshop
spec:
  type: ClusterIP  # Changed from NodePort
  selector:
    app: reactjs-frontend
  ports:
    - port: 80        # Service port
      targetPort: 80  # Container port
      protocol: TCP
