apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  WORDPRESS_DB_HOST: {{ .Values.database.host }}
  WORDPRESS_DB_NAME: {{ .Values.database.name }}
  WORDPRESS_DB_USER: {{ .Values.database.user }}
  WORDPRESS_DB_PASSWORD: {{ .Values.database.password }}
