apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: reactjs
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30011
