apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: reactjs
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      name: laravel
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: devidevops447/laravel-beta:v27
          ports:
            - containerPort: 80