apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: reactjs
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32010
