apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: reactjs
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: devidevops447/reactjs-frontend-beta:test55
          ports:
            - containerPort: 80