apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-chd-pvc
  namespace: workshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3
