apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bharatyatra-ui
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - host: bharatyatra-ui.showmysite.click
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prod-bharatyatra-ui-service
              port:
                number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bharatyatra-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - host: bharatyatra-api.showmysite.click
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prod-bharatyatra-api-service
              port:
                number: 5000
