apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
- ../../base
- ingress.yaml
- namespace.yaml

images:
- name: devidevops447/bharatyatra-backend
  newTag: v11
- name: devidevops447/bharatyatra-frontend
  newTag: b12